allow_cmd_list = [
    "set pressure_in shift",
    "set pressure_in radial",
    "set pressure_out shift",
    "set pressure_out radial",
    "set mq2 shift",
    "set mq2 radial",
    "set mq2_2 shift",
    "set mq2_2 radial",
    "set mq7 shift",
    "set mq7 radial",
    "set hx711 ch",
    "set hx711 shift",
    "set hx711 radial",
    "set buzzer on",
    "set buzzer off",
    "set heater on",
    "set heater off",
    "set valveOpen on",
    "set valveOpen off",
    "set valveClose on",
    "set valveClose off",
    "log on",
    "log off",
    "help"
]
